# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.19"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "payload"
languages = ["CXX"]
cmake-before = "set(CMAKE_CONFIGURATION_TYPES Debug Release)"
include-after = ["cmake/riscvm.cmake"]
msvc-runtime = "static"

[template.riscvm]
type = "executable"
add-function = "add_riscvm_executable"

# Windows implementation of the riscvm syscalls (for debugging only)
[target.riscvm-crt0]
type = "shared"
sources = ["src/riscvm-crt0.cpp"]

[target.payload]
type = "riscvm"
sources = [
	"src/main.cpp",
	"src/phnt.h",
]
link-libraries = [
    "riscvm-crt0",
    "ntdll.lib",
]
compile-features = ["cxx_std_17"]
msvc.link-options = [
	"/INCREMENTAL:NO",
	"/DEBUG",
]
